import { Poppins } from "next/font/google";
import "./globals.css";
import { SessionWrapper } from "./components/SessionWrapper";

import { ReduxProvider } from "./redux/ReduxProvider";
import GradientWrapper from "./components/GradientWrapper";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Web Hunter",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased light`}
        style={{ fontFamily: "var(--font-poppins)" }}
      >
        <SessionWrapper>
          <ReduxProvider>
            <GradientWrapper children={children} />
          </ReduxProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
